include:
  - project: 'smartive/ci-templates'
    ref: v1.3.1
    file: '/github/defaults/npm.yml'

variables:
  REPO: 'smartive/giuseppe'

create release:
  before_script:
    - npm ci
    - npm run build
